common:
  per_page: 20
orders:
  status: {open: "open", deliver: "deliver", close: "close"}
pictures:
  upload_dir: "uploads"
  accepted_files: "image/jpeg, image/gif, image/png"
  max_size: 5
  avatar_size: "128"
  avatar_small_size: "24"
